[static_config]
my_id = "multi_sub"
host = "127.0.0.1"
port = 5561
is_master = false
publish_hz = 0
subscribe_hz = 500

[static_config.subscribers]
from_multi_pub = "multi_pub"
from_pub       = "pub_node"

[dynamic]
